version: '3'
services:
  basic-flask-app:
    build: ${PROJECTS_HOME}/basic-flask-app
    ports:
      - "8080:8080"
  basic-sanic-app:
    build: ${PROJECTS_HOME}/basic-sanic-app
    ports:
      - "8000:8000"
